name: Build and publish docker image

on:
  push:
    branches:
      - main

jobs:
  build-publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Required for reading the repository contents
      packages: write     # Required for pushing to GitHub Packages
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short Git SHA
        id: vars
        run: echo "sha=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build the docker image
        run: |
          docker build -f Dockerfile-prod --build-arg VITE_MANAGEMENT_ROOT_URL=https://admin.cloud.open-dpp.de --build-arg VITE_AUTH_ROOT_URL=https://auth.cloud.open-dpp.de --build-arg VITE_API_ROOT_URL=https://api.cloud.open-dpp.de --build-arg VITE_AGENT_SERVER_ROOT=https://agent-server.cloud.open-dpp.de --build-arg VITE_MEDIA_SERVICE_ROOT=https://media.cloud.open-dpp.de . -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:${{ env.sha }}

      - name: Push the docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ env.sha }}



